id: protect-admin-pages
title: "Create RBAC Middleware to Restrict Admin Pages by User Role"
description: |
  Implement a role-based access control (RBAC) middleware to protect admin pages from unauthorized access.
  This is a critical security feature for applications with different user roles and permissions.
requirements:
  - Add a `role` field to the `User` model in `schema.prisma` (e.g., `USER`, `ADMIN`).
  - Create a middleware that checks the user's role based on their JWT.
  - The middleware should protect all routes under `/admin/*`.
  - If a non-admin user tries to access an admin route, they should be redirected to a `403 Forbidden` page.
difficulty: hard
estimated_time: 100
tags: [security, rbac, middleware, authorization]
files_to_modify:
  - db/prisma/schema.prisma
  - src/middleware/rbac.ts
  - src/app/admin/page.tsx
success_criteria:
  - Admin routes are protected and can only be accessed by users with the `ADMIN` role.
  - Non-admin users are redirected to a forbidden page when trying to access admin routes.
  - The tests verify that the RBAC middleware correctly restricts access based on user roles.
