id: schema-migration-safety
title: "CLI Tool to Warn on Destructive Prisma Migrations"
description: |
  Create a command-line interface (CLI) tool that inspects a Prisma migration SQL file and warns the user if it contains potentially destructive changes (e.g., `DROP TABLE`, `DROP COLUMN`).
  This tool will help prevent accidental data loss during database migrations.
requirements:
  - Create a new CLI script `src/scripts/check-migration.ts`.
  - The script should take a file path to a SQL migration file as an argument.
  - It should read the SQL file and check for destructive commands like `DROP` and `TRUNCATE`.
  - If a destructive command is found, the script should print a warning message to the console and exit with a non-zero status code.
  - The script should be executable from the command line.
difficulty: hard
estimated_time: 120
tags: [cli, prisma, database, migration]
files_to_modify:
  - src/scripts/check-migration.ts
success_criteria:
  - The CLI tool correctly identifies destructive SQL commands in a migration file.
  - The tool prints a warning message and exits with a non-zero status code when a destructive command is found.
  - The tool exits with a zero status code when no destructive commands are found.
  - The tests verify the tool's behavior with both safe and destructive SQL files.
