id: add-auth-rate-limiting
title: "Rate-limit Authentication Endpoints"
description: |
  Add rate limiting for login and register routes to prevent brute-force attacks.
  Apply limits per-IP and per-user basis using Redis or in-memory cache.
requirements:
  - Add middleware to limit `/api/auth/login` and `/api/auth/register`
  - Log blocked attempts to DB
  - Use sliding window algorithm or external rate-limit lib
difficulty: hard
estimated_time: 60
tags: [security, middleware, rate-limiting]
files_to_modify:
  - src/app/api/auth/login/route.ts
  - src/middleware/rateLimit.ts
success_criteria:
  - 429 status returned on repeated abuse
  - Different IPs treated separately
  - Tests simulate abuse and verify lockouts
