id: failover-db-reconnect
title: "Implement Prisma Retry Logic with Exponential Backoff on DB Downtime"
description: |
  Enhance the application's resilience by adding a custom Prisma client extension that implements retry logic with exponential backoff for handling database connection errors.
  This ensures that the application can gracefully handle temporary database downtime without crashing.
requirements:
  - Create a Prisma client extension that intercepts query operations.
  - The extension should catch database connection errors (e.g., P1001).
  - Implement a retry mechanism with exponential backoff, retrying the query up to 5 times with increasing delays.
  - The extension should be applied to the Prisma client instance.
difficulty: hard
estimated_time: 100
tags: [database, resilience, prisma, extension]
files_to_modify:
  - src/lib/prisma.ts
success_criteria:
  - The application does not crash when the database is temporarily unavailable.
  - Database queries are automatically retried with exponential backoff.
  - The tests simulate a database connection error and verify that the retry logic is triggered.
