id: session-audit-log
title: "Track User Session and Token Actions in Audit Log"
description: |
  Implement a comprehensive session audit log that tracks user login, logout, and token refresh actions.
  This is a critical security feature for monitoring user activity and detecting potential threats.
  The audit log should also capture the user's IP address and user agent for each action.
requirements:
  - Create a new `AuditLog` model in `schema.prisma` with fields for `userId`, `action`, `ipAddress`, and `userAgent`.
  - In the login route, create an audit log entry for successful logins.
  - In the logout route, create an audit log entry for logouts.
  - Implement a token refresh endpoint that generates a new JWT and logs the refresh action.
  - The token refresh endpoint must be protected and require a valid, non-expired refresh token.
difficulty: hard
estimated_time: 90
tags: [security, audit-log, session-management, authentication]
files_to_modify:
  - db/prisma/schema.prisma
  - src/app/api/auth/login/route.ts
  - src/app/api/auth/logout/route.ts
  - src/app/api/auth/refresh/route.ts
success_criteria:
  - Audit log entries are created for login, logout, and token refresh events.
  - The audit log entries contain the correct user ID, action, IP address, and user agent.
  - The token refresh endpoint successfully returns a new JWT.
  - The refresh endpoint is secure and cannot be accessed without a valid refresh token.
